version: "3"
services:
  web:
    container_name: "web"
    build: ./frontend
    env_file:
      - .env
    ports:
      - 3500:${WEB_PORT}
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: dev -p ${WEB_PORT}
    depends_on:
      - api
  api:
    container_name: "api"
    build: ./backend
    env_file:
      - .env
    ports:
      - 4000:${API_PORT}
    working_dir: /backend
    volumes:
      - ./backend:/backend
    command: dev
    depends_on:
      - postgres_dev
  postgres_dev:
    container_name: "postgres-dev"
    image: "postgres:14.1-alpine"
    env_file:
      - .env
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
