version: "3"
services:
  web:
    container_name: "web"
    build: ./frontend
    ports:
      - 3500:3499
    working_dir: /frontend
    volumes:
      - ../frontend:/frontend
    command: dev
    depends_on:
      - api
  api:
    container_name: "api"
    build: ./backend
    ports:
      - 4000:3999
    working_dir: /backend
    volumes:
      - ../backend:/backend
    command: dev
    env_file:
      - ../backend/.env
    depends_on:
      - postgres_dev
  postgres_dev:
    container_name: "postgres-dev"
    image: "postgres:14.1-alpine"
    env_file:
      - ../.env
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
volumes:
  postgres_data:
